name: Ejecutar análisis de sentimientos 2

on:
  workflow_dispatch:   # ejecución manual desde GitHub Actions
  schedule:
     - cron: "0 6 * * *"     # diaria a las 6 AM UTC
  #  - cron: "0 6 * * 1"     # semanal (lunes) a las 6 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python script_procesar_analysis_sent.py
