# Este workflow ejecuta tu script de análisis de sentimientos.
# Incluye 3 formas de ejecución:
# 1. Manual → desde GitHub Actions (workflow_dispatch)
# 2. Automática diaria → todos los días a las 6 AM UTC
# 3. Automática semanal → cada lunes a las 6 AM UTC

name: Ejecutar análisis de sentimientos

on:
  workflow_dispatch:   # ejecución manual desde GitHub Actions
  #schedule:
  #  - cron: "0 6 * * *"     # diaria a las 6 AM UTC
  #  - cron: "0 6 * * 1"     # semanal (lunes) a las 6 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          python script_procesar_analysis_sent.py


          
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          python tu_script.py
